export default function WheelTitle() {
  return (
    <h1 className="scroll-m-20 text-center text-4xl font-extrabold tracking-tight text-balance">
      TODO this text is going to be autogenerated by AI based on content.
    </h1>
  );
}
